// THE one constants file for the level curve and the XP-per-token rate —
// no other file holds these numbers. The curve is frozen as data so it can be
// recalibrated without code changes.

export type Stage = 'baby' | 'young-baby' | 'teen' | 'older-teen' | 'adult';

// Calibration target: ~400k real input+output tokens/day × 5 XP/1k ≈ 2.000 XP/day
// → L32 (120.000 XP) in ~60 days for a reference user.
export const XP_PER_1K_TOKENS = 5;

// Total XP required to reach the level cap (L32). The curve is cumulative
// quadratic: cumXP(L) = round(120000 × L² / 32²). Level 1 is defined as 0 XP.
const LEVEL_CAP = 32;

// Frozen level table derived from the formula above. Index 0 = Level 1.
// Generated by: cumXP(L) = round(TOTAL_XP * L^2 / LEVEL_CAP^2), with L=1 forced to 0.
export const LEVEL_XP_THRESHOLDS: ReadonlyArray<number> = [
  0, // L1
  469, // L2
  1055, // L3
  1875, // L4
  2930, // L5
  4219, // L6
  5742, // L7
  7500, // L8
  9492, // L9
  11719, // L10
  14180, // L11
  16875, // L12
  19805, // L13
  22969, // L14
  26367, // L15
  30000, // L16
  33867, // L17
  37969, // L18
  42305, // L19
  46875, // L20
  51680, // L21
  56719, // L22
  61992, // L23
  67500, // L24
  73242, // L25
  79219, // L26
  85430, // L27
  91875, // L28
  98555, // L29
  105469, // L30
  112617, // L31
  120000, // L32
];

// Level at which each stage begins. The stage strings match the sheet file
// names (beaver-<stage>.png/.json) so the renderer can load them directly.
const STAGE_ANCHORS: ReadonlyArray<{ readonly level: number; readonly stage: Stage }> = [
  { level: 1, stage: 'baby' },
  { level: 5, stage: 'young-baby' },
  { level: 9, stage: 'teen' },
  { level: 17, stage: 'older-teen' },
  { level: 25, stage: 'adult' },
];

export function levelForXp(xp: number): number {
  const clamped = Math.max(0, xp);
  let level = 1;
  for (let i = 1; i < LEVEL_XP_THRESHOLDS.length; i += 1) {
    if (clamped >= LEVEL_XP_THRESHOLDS[i]) {
      level = i + 1;
    } else {
      break;
    }
  }
  return level;
}

export function xpForLevel(level: number): number {
  const idx = Math.max(1, Math.min(LEVEL_CAP, level)) - 1;
  return LEVEL_XP_THRESHOLDS[idx];
}

export function stageForLevel(level: number): Stage {
  let stage: Stage = STAGE_ANCHORS[0].stage;
  for (const anchor of STAGE_ANCHORS) {
    if (level >= anchor.level) stage = anchor.stage;
  }
  return stage;
}
